version: '2.1'

services:
  maildev:
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
  
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16685:16685"
      - "16686:16686"
      - "14268"
      - "14250"  

  webapp1:
    environment:
      - ASPNETCORE_URLS=http://localhost:8080
    build:
      context: ../src
      dockerfile: SendMail/Dockerfile
    network_mode: "host"
    
  webapp2:
    environment:
      - ASPNETCORE_URLS=http://localhost:8081
    build:
      context: ../src
      dockerfile: SendMail/Dockerfile
    network_mode: "host"
    
  consul:
    image: hashicorp/consul
    command: "agent -dev -client=0.0.0.0"
    ports:
    - "8500:8500"
    - "8600:8600/tcp"
    - "8600:8600/udp"